const {chromium}=require(process.env.WIKI_PLAYWRIGHT);
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 fs.mkdirSync('wiki-preview',{recursive:true});
 for(const [width,height] of [[360,800],[412,915],[690,800],[768,900],[1280,900]]){
  const context=await browser.newContext({viewport:{width,height},isMobile:width<1100,hasTouch:width<1100,userAgent:width<1100?'Mozilla/5.0 Chrome/130.0.0.0 Mobile LegendsWikiAndroid/5':undefined});
  const page=await context.newPage(),errors=[],iconRequests=[];page.on('request',r=>{if(r.url().includes('/graphics/pokemon/'))iconRequests.push(r.url());});page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765/wiki/');await page.locator('.topic-cards').waitFor();
  assert.equal(await page.locator('.topic-cards .card').count(),7);
  assert(await page.getByRole('link',{name:'Open LegendsDex',exact:true}).isVisible());
  assert.equal(await page.locator('.wiki-mobile-nav a').count(),2);
  await page.getByRole('link',{name:'Open LegendsDex',exact:true}).click();
  await page.locator('.route-card').first().waitFor();
  assert(await page.getByRole('link',{name:'Back to guide',exact:true}).isVisible());
  assert.equal(await page.locator('.mobile-nav button').count(),2);
  assert.equal(await page.locator('.mobile-nav a').count(),0);
  await page.getByRole('link',{name:'Back to guide',exact:true}).click();await page.locator('.topic-cards').waitFor();
  async function noOverflow(){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow at '+width);}
  await noOverflow();await page.screenshot({path:`wiki-preview/home-${width}.png`,fullPage:true});
  await page.locator('.topic-cards [data-category="Customization"]').click();
  await page.getByRole('heading',{name:'Customization',exact:true}).waitFor();
  await page.locator('#content [data-page="wardrobe"]').click();
  await page.getByRole('heading',{name:'Wardrobe, costumes, and footwear',exact:true}).waitFor();await noOverflow();
  await page.goBack();await page.getByRole('heading',{name:'Customization',exact:true}).waitFor();
  await page.goBack();await page.locator('.topic-cards').waitFor();
  await page.getByLabel('Search wiki',{exact:true}).fill('boots');assert(await page.locator('#cards [data-page="wardrobe"]').isVisible());
  await page.goto('http://127.0.0.1:8765/wiki/dex.html?view=species');
  await page.locator('.dex-card').first().waitFor();
  assert.equal(await page.locator('.dex-card').count(),1026,'all Pokémon render before scrolling');
  assert.equal(await page.locator('.dex-card .sprite-ready .sprite-art').count(),1026,'all sprites are ready');
  assert(await page.locator('#more').isHidden(),'no incremental loading');
  assert(!await page.locator('#return-to-search').isVisible(),'arrow hides above the search anchor');
  await page.evaluate(()=>scrollTo({top:1600,behavior:'instant'}));
  await page.waitForFunction(()=>document.querySelector('#return-to-search').classList.contains('is-visible'));
  const before=await page.evaluate(()=>scrollY);
  if(width<1100)await page.locator('[data-mobileview="routes"]').click();
  else await page.evaluate(()=>document.querySelector('[data-view="routes"]').click());
  assert(Math.abs(await page.evaluate(()=>scrollY)-before)<3,'switching to Routes preserves scroll');
  if(width<1100)await page.locator('[data-mobileview="species"]').click();
  else await page.evaluate(()=>document.querySelector('[data-view="species"]').click());
  assert(Math.abs(await page.evaluate(()=>scrollY)-before)<3,'switching to Pokédex preserves scroll');
  await page.screenshot({path:`wiki-preview/scroll-${width}.png`,fullPage:false});
  await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));
  assert.equal(await page.locator('.dex-card').count(),1026);
  assert.deepEqual(iconRequests,[],'scrolling must not request individual sprites');
  await page.locator('#return-to-search').click();
  await page.waitForFunction(()=>{const y=document.querySelector('#search-anchor').getBoundingClientRect().top;return y>=10&&y<=15;});
  await page.waitForFunction(()=>!document.querySelector('#return-to-search').classList.contains('is-visible'));
  assert(await page.locator('#return-to-search').isDisabled());
  assert(await page.evaluate(()=>scrollY>100),'return arrow uses search, not page top');
  // Quick direction changes during the departure/cooldown cannot reactivate the control.
  if(width===412){
    await page.waitForFunction(()=>Number(getComputedStyle(document.querySelector('.rotom-companion')).opacity)>.95);
    await page.screenshot({path:'wiki-preview/rotom-flight.png',fullPage:false});
    await page.evaluate(()=>scrollTo({top:1600,behavior:'instant'}));
    assert(await page.locator('#return-to-search').isDisabled(),'cooldown blocks rapid reappearance');
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').classList.contains('is-flying'));
    assert(await page.locator('#return-to-search').isDisabled(),'brief cooldown remains after flight');
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').disabled);
    // Manually reaching the search anchor also departs, without requiring a click.
    await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
    await page.waitForFunction(()=>document.querySelector('#return-to-search').classList.contains('is-flying'));
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').classList.contains('is-flying'));
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.evaluate(()=>scrollTo({top:1600,behavior:'instant'}));
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').disabled);
    await page.locator('#return-to-search').click();
    await page.waitForFunction(()=>document.querySelector('#return-to-search').disabled);
    assert(!await page.locator('#return-to-search').evaluate(e=>e.classList.contains('is-flying')),'reduced motion skips flight');
    await page.emulateMedia({reducedMotion:'no-preference'});
  }
  await page.locator('#search').fill('Bulbasaur');
  assert.equal(await page.locator('.dex-card').count(),1);await noOverflow();
  const reply=page.waitForResponse(r=>r.url().endsWith('/cries/bulbasaur.wav'));
  await page.getByRole('button',{name:'Play Bulbasaur cry',exact:true}).click();assert((await reply).ok(),'cry request failed');
  await page.getByRole('status').filter({hasText:'Playing Bulbasaur'}).waitFor();assert(!await page.locator('#detail').isVisible());
  await page.locator('.dex-card [data-species="BULBASAUR"]').click();await page.locator('#detail').waitFor();
  assert.equal(await page.locator('button button').count(),0,'nested interactive controls');await noOverflow();
  await page.locator('#close-detail').click();
  await page.locator('#search').fill('Poochyena');
  await page.locator('.dex-card [data-species="POOCHYENA"]').click();
  assert.equal(await page.locator('#detail').evaluate(e=>e.scrollTop),0,'profile opens at the top');
  assert(await page.locator('#toggle-entry').isVisible());
  assert(await page.locator('#pokedex-entry').isHidden());
  await page.locator('#toggle-entry').click();
  assert(await page.locator('#pokedex-entry').isVisible());
  assert((await page.locator('#pokedex-entry').innerText()).includes('It savagely threatens foes'));
  assert.equal(await page.locator('#toggle-entry').getAttribute('aria-expanded'),'true');
  await noOverflow();
  await page.screenshot({path:`wiki-preview/profile-${width}.png`,fullPage:false});
  await page.locator('#detail').evaluate(e=>e.scrollTop=e.scrollHeight);
  assert(await page.locator('.encounter-map').isVisible());
  assert(await page.locator('.map-highlight').count()>0);
  const closeBounds=await page.locator('#close-detail').boundingBox(),dialogBounds=await page.locator('#detail').boundingBox();
  assert(closeBounds.y<dialogBounds.y+55&&closeBounds.x>dialogBounds.x+dialogBounds.width-60,'close remains at top right while scrolling');
  await page.screenshot({path:`wiki-preview/encounter-map-${width}.png`,fullPage:false});
  await page.locator('#close-detail').click();
  await page.locator('.dex-card [data-species="POOCHYENA"]').click();
  assert.equal(await page.locator('#detail').evaluate(e=>e.scrollTop),0,'reopening resets previous profile scroll');
  assert(await page.locator('#pokedex-entry').isHidden(),'entry disclosure resets');
  await page.locator('#close-detail').click();
  await page.locator('#search').fill('');await page.locator('#type').selectOption('FIRE');
  assert((await page.locator('.dex-card .types').allTextContents()).every(t=>t.includes('fire')));
  await page.screenshot({path:`wiki-preview/dex-${width}.png`,fullPage:false});
  // A live resize preserves both the current page and selected filter.
  if(width===412){await page.setViewportSize({width:690,height:800});assert.equal(await page.locator('#type').inputValue(),'FIRE');await noOverflow();}
  await page.goto('http://127.0.0.1:8765/wiki/dex.html?view=routes');await page.locator('.route-card').first().waitFor();await noOverflow();
  await page.screenshot({path:`wiki-preview/routes-${width}.png`,fullPage:false});
  await page.locator('#method').selectOption('surf');await page.locator('[data-view="species"]').click();await page.locator('#type').selectOption('all');
  assert((await page.locator('#results-count').innerText()).startsWith('1026 '),'hidden route method must not filter the National Dex');
  assert.equal(await page.locator('.hero').evaluate(e=>getComputedStyle(e,'::before').content),'none');
  assert.deepEqual(errors,[]);await context.close();
 }
 await browser.close();console.log('PASS: browser navigation, search, cries, profile controls, types and overflow at 360/412/690/768/1280px, plus live fold-size change');
})().catch(e=>{console.error(e);process.exit(1);});
