const {chromium}=require(process.env.WIKI_PLAYWRIGHT);
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 fs.mkdirSync('wiki-preview',{recursive:true});
 for(const [width,height] of [[360,800],[412,915],[690,800],[768,900],[1280,900]]){
  const context=await browser.newContext({viewport:{width,height},isMobile:width<1100,hasTouch:width<1100,userAgent:width<1100?'Mozilla/5.0 Chrome/130.0.0.0 Mobile LegendsWikiAndroid/5':undefined});
  // An app may have the old JSON cached under the unversioned URL.
  await context.route(/\/walkthrough-maps\.json$/,route=>route.fulfill({contentType:'application/json',body:JSON.stringify({regions:null})}));
  const page=await context.newPage(),errors=[],iconRequests=[];page.on('request',r=>{if(r.url().includes('/graphics/pokemon/'))iconRequests.push(r.url());});page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765/wiki/');await page.locator('.topic-cards').waitFor();
  assert.equal(await page.locator('.topic-cards .card').count(),7);
  assert(await page.getByRole('link',{name:'Open LegendsDex',exact:true}).isVisible());
  assert.equal(await page.locator('.wiki-mobile-nav a').count(),2);
  assert.deepEqual(await page.locator('.wiki-mobile-nav span').allTextContents(),['Walkthrough','LegendsDex']);
  assert.equal(await page.locator('.wiki-mobile-nav a').last().getAttribute('href'),'dex.html?view=routes');
  await page.getByRole('link',{name:'Open LegendsDex',exact:true}).click();
  await page.locator('.route-card').first().waitFor();
  assert(await page.getByRole('link',{name:'Back to guide',exact:true}).isVisible());
  assert.equal(await page.locator('.mobile-nav button').count(),2);
  assert.equal(await page.locator('.mobile-nav a').count(),0);
  await page.getByRole('link',{name:'Back to guide',exact:true}).click();await page.locator('.topic-cards').waitFor();
  async function noOverflow(){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow at '+width);}
  await noOverflow();await page.screenshot({path:`wiki-preview/home-${width}.png`,fullPage:true});
  if(width<1100)await page.locator('.wiki-mobile-nav [data-page="walkthrough"]').click();
  else await page.getByRole('link',{name:'Walkthrough',exact:false}).first().click();
  await page.getByRole('heading',{name:'Game walkthrough: start your adventure',exact:true}).waitFor();await noOverflow();
  assert(await page.locator('.wiki-mobile-nav').isHidden(),'walkthrough hides encounter navigation');
  assert.equal(await page.locator('.walkthrough-stops a').count(),14);
  assert.equal(await page.locator('.chapter-group').count(),2);
  assert.equal(await page.locator('.chapter-group').first().locator('a').count(),10);
  assert.equal(await page.locator('.chapter-group').last().locator('a').count(),4);
  await page.locator('#next-chapter-group').click();
  await page.waitForFunction(()=>document.querySelector('#chapter-group-label').textContent==='Chapters 11–14 of 14');
  assert(await page.locator('#next-chapter-group').isDisabled());
  await page.locator('#previous-chapter-group').click();
  await page.waitForFunction(()=>document.querySelector('#chapter-group-label').textContent==='Chapters 1–10 of 14');
  if(width===412){await page.locator('.chapter-browser').scrollIntoViewIfNeeded();await page.screenshot({path:'wiki-preview/compact-chapters.png'});}
  await page.locator('.region-map-explorer svg').waitFor();
  assert(await page.locator('.region-map-canvas svg').evaluate(e=>e.getBoundingClientRect().height>100),'map has visible height');
  assert.equal(await page.locator('.map-town-picker option').count(),17);
  assert.equal(await page.locator('.chapter-group a strong').first().innerText(),'New Game');
  assert.equal(await page.locator('.region-map-explorer .walkthrough-map-highlight').count(),0);
  await page.getByRole('button',{name:'Littleroot Town',exact:true}).click();
  assert((await page.locator('.map-town-name').innerText()).includes('Littleroot'));
  await page.locator('[data-region-map="Kanto"]').click();
  await page.getByRole('button',{name:'Pallet Town',exact:true}).focus();await page.keyboard.press('Enter');
  assert((await page.locator('.map-town-name').innerText()).includes('Pallet'));
  await page.locator('[data-region-map="Hoenn"]').click();await noOverflow();
  if(width===412)await page.screenshot({path:'wiki-preview/walkthrough-stops.png',fullPage:false});
  await page.locator('#walkthrough-town').selectOption('walkthrough-rustboro#section-prepare-in-rustboro');
  await page.getByRole('heading',{name:'Prepare in Rustboro',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelectorAll('.walkthrough-field-guide').length===8);
  assert.equal(await page.locator('[data-route="MAP_RUSTURF_TUNNEL"] li').count(),1);
  assert((await page.locator('[data-route="MAP_RUSTURF_TUNNEL"]').innerText()).includes('100%'));
  assert(await page.locator('#section-prepare-in-rustboro').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=50&&r.top<innerHeight/2;}),'town jump reaches its section beneath header');
  if(width===412)await page.locator('[data-walkthrough-section="section-follow-the-devon-theft"]').screenshot({path:'wiki-preview/walkthrough-route116.png'});
  await page.reload();await page.locator('#walkthrough-town').waitFor();
  await page.waitForFunction(()=>document.querySelectorAll('.walkthrough-field-guide').length===8);
  assert.equal(await page.locator('#walkthrough-town').inputValue(),'walkthrough-rustboro#section-prepare-in-rustboro');
  await page.locator('.walkthrough-navigation [data-page="walkthrough"]').click();
  await page.getByRole('heading',{name:'Game walkthrough: start your adventure',exact:true}).waitFor();
  await page.locator('.articlebody [data-page="walkthrough-littleroot"]').first().click();
  await page.getByRole('heading',{name:'Chapter 1: Littleroot and your first Pokémon',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelectorAll('.walkthrough-field-guide').length===7);
  assert.equal(await page.getByRole('heading',{name:'Your goal',exact:true}).count(),0);
  assert(await page.locator('.chapter-intro-tip img').isVisible());
  if(width===412){await page.locator('.chapter-intro-tip').scrollIntoViewIfNeeded();await page.screenshot({path:'wiki-preview/compact-rotom-hint.png'});}
  assert.equal(await page.locator('[data-route="MAP_ROUTE103"] .walkthrough-method').count(),5);
  assert(!(await page.locator('[data-route="MAP_ROUTE103"] details').getAttribute('open')));
  await page.locator('[data-route="MAP_ROUTE103"] summary').click();
  assert(await page.locator('[data-route="MAP_ROUTE103"] details').evaluate(e=>e.open));
  await noOverflow();
  await page.locator('[data-route="MAP_ROUTE103"] summary').click();
  assert((await page.locator('.articlebody').innerText()).includes('level 2 Stunky'));await noOverflow();
  if(width===412)await page.screenshot({path:'wiki-preview/walkthrough-chapter.png',fullPage:false});
  assert.equal(await page.locator('.chapter-sequence .chapter-step').count(),1);
  if(width===412){
   await page.goto('http://127.0.0.1:8765/wiki/?page=walkthrough-rustboro');
   await page.locator('.chapter-sequence').waitFor();
   const next=['dewford','slateport','mauville','meteor-falls','lavaridge','norman','fortree','lilycove','mossdeep','sootopolis','league'];
   for(const [i,slug] of next.entries()){
    await page.locator('.chapter-sequence .chapter-step').last().click();
    await page.waitForFunction(id=>new URLSearchParams(location.search).get('page')===id,'walkthrough-'+slug);
    await page.locator('.walkthrough-field-guide').first().waitFor();await noOverflow();
    assert((await page.locator('h1').innerText()).startsWith('Chapter '+(i+4)+':'));
    assert.equal(await page.locator('.chapter-sequence .chapter-step').count(),i===10?1:2);
   }
   await page.locator('.chapter-sequence .chapter-step').first().click();
   await page.getByRole('heading',{name:/Chapter 13:/}).waitFor();
  }
  await page.locator('#home').click();await page.locator('.topic-cards').waitFor();if(width<1100)assert(await page.locator('.wiki-mobile-nav').isVisible(),'leaving walkthrough restores bottom navigation');
  await page.locator('.topic-cards [data-category="Customization"]').click();
  await page.getByRole('heading',{name:'Customization',exact:true}).waitFor();
  await page.locator('#content [data-page="wardrobe"]').click();
  await page.getByRole('heading',{name:'Wardrobe, costumes, and footwear',exact:true}).waitFor();await noOverflow();
  assert.deepEqual(await page.locator('.wiki-mobile-nav span').allTextContents(),['Walkthrough','LegendsDex']);
  await page.goBack();await page.getByRole('heading',{name:'Customization',exact:true}).waitFor();
  await page.goBack();await page.locator('.topic-cards').waitFor();
  await page.getByLabel('Search wiki',{exact:true}).fill('boots');assert(await page.locator('#cards [data-page="wardrobe"]').isVisible());
  await page.goto('http://127.0.0.1:8765/wiki/dex.html?view=species');
  await page.locator('.dex-card').first().waitFor();
  assert.equal(await page.locator('.dex-card').count(),1026,'all Pokémon render before scrolling');
  assert.equal(await page.locator('.dex-card .sprite-ready .sprite-art').count(),1026,'all sprites are ready');
  assert(await page.locator('#more').isHidden(),'no incremental loading');
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
  await page.waitForFunction(()=>!document.querySelector('#return-to-search').classList.contains('is-visible'));
  assert(!await page.locator('#return-to-search').isVisible(),'arrow hides above the search anchor');
  await page.evaluate(()=>scrollTo({top:1600,behavior:'instant'}));
  await page.waitForFunction(()=>document.querySelector('#return-to-search').classList.contains('is-visible'));
  const before=await page.evaluate(()=>scrollY);
  if(width<1100)await page.locator('[data-mobileview="routes"]').click();
  else await page.evaluate(()=>document.querySelector('[data-view="routes"]').click());
  assert(Math.abs(await page.evaluate(()=>scrollY)-before)<3,'switching to Routes preserves scroll');
  if(width<1100)await page.locator('[data-mobileview="species"]').click();
  else await page.evaluate(()=>document.querySelector('[data-view="species"]').click());
  assert(Math.abs(await page.evaluate(()=>scrollY)-before)<3,'switching to Pokédex preserves scroll');
  await page.screenshot({path:`wiki-preview/scroll-${width}.png`,fullPage:false});
  await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));
  assert.equal(await page.locator('.dex-card').count(),1026);
  assert.deepEqual(iconRequests,[],'scrolling must not request individual sprites');
  await page.locator('#return-to-search').click();
  await page.waitForFunction(()=>{const y=document.querySelector('#search-anchor').getBoundingClientRect().top;return y>=10&&y<=15;});
  await page.waitForFunction(()=>!document.querySelector('#return-to-search').classList.contains('is-visible'));
  assert(await page.locator('#return-to-search').isDisabled());
  assert(await page.evaluate(()=>scrollY>100),'return arrow uses search, not page top');
  // Quick direction changes during the departure/cooldown cannot reactivate the control.
  if(width===412){
    await page.waitForFunction(()=>{const rotom=document.querySelector('.rotom-companion');return Number(getComputedStyle(rotom).opacity)>.95&&rotom.complete&&rotom.naturalWidth>0;});
    await page.screenshot({path:'wiki-preview/rotom-flight.png',fullPage:false});
    await page.evaluate(()=>scrollTo({top:1600,behavior:'instant'}));
    assert(await page.locator('#return-to-search').isDisabled(),'cooldown blocks rapid reappearance');
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').classList.contains('is-flying'));
    assert(await page.locator('#return-to-search').isDisabled(),'brief cooldown remains after flight');
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').disabled);
    // Manually reaching the search anchor also departs, without requiring a click.
    await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
    await page.waitForFunction(()=>document.querySelector('#return-to-search').classList.contains('is-flying'));
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').classList.contains('is-flying'));
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.evaluate(()=>scrollTo({top:1600,behavior:'instant'}));
    await page.waitForFunction(()=>!document.querySelector('#return-to-search').disabled);
    await page.locator('#return-to-search').click();
    await page.waitForFunction(()=>document.querySelector('#return-to-search').disabled);
    assert(!await page.locator('#return-to-search').evaluate(e=>e.classList.contains('is-flying')),'reduced motion skips flight');
    await page.emulateMedia({reducedMotion:'no-preference'});
  }
  await page.locator('#search').fill('Bulbasaur');
  assert.equal(await page.locator('.dex-card').count(),1);await noOverflow();
  const reply=page.waitForResponse(r=>r.url().endsWith('/cries/bulbasaur.wav'));
  await page.getByRole('button',{name:'Play Bulbasaur cry',exact:true}).click();assert((await reply).ok(),'cry request failed');
  await page.getByRole('status').filter({hasText:'Playing Bulbasaur'}).waitFor();assert(!await page.locator('#detail').isVisible());
  await page.locator('.dex-card [data-species="BULBASAUR"]').click();await page.locator('#detail').waitFor();
  assert.equal(await page.locator('button button').count(),0,'nested interactive controls');await noOverflow();
  await page.locator('#close-detail').click();
  await page.locator('#search').fill('Poochyena');
  await page.locator('.dex-card [data-species="POOCHYENA"]').click();
  assert.equal(await page.locator('#detail').evaluate(e=>e.scrollTop),0,'profile opens at the top');
  assert(await page.locator('#toggle-entry').isVisible());
  await page.waitForFunction(()=>{const hint=document.querySelector('.rotom-tip img');return hint.complete&&hint.naturalWidth>0;});
  assert(await page.locator('#pokedex-entry').isHidden());
  assert(await page.locator('#toggle-shiny').isEnabled(),'shiny portraits preload before first profile');
  await page.locator('#toggle-shiny').click();
  assert.equal(await page.locator('#toggle-shiny').getAttribute('aria-pressed'),'true');
  assert(await page.locator('.detail-top .sprite-art').evaluate(e=>e.classList.contains('is-shiny')));
  assert.equal(await page.locator('.shiny-sparkles i').count(),8);
  await page.waitForFunction(()=>document.querySelector('#cry-status').textContent==='Shiny encounter!');
  if(width===412){await page.waitForTimeout(220);await page.screenshot({path:'wiki-preview/shiny-sparkles.png',fullPage:false});}
  await page.locator('#toggle-shiny').click();assert.equal(await page.locator('.shiny-sparkles').count(),0,'toggling back cancels sparkles');
  assert.equal(await page.locator('#toggle-shiny').getAttribute('aria-pressed'),'false');
  await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#toggle-shiny').click();
  assert.equal(await page.locator('.shiny-sparkles').count(),0,'reduced motion omits the burst');
  await page.locator('#toggle-shiny').click();await page.emulateMedia({reducedMotion:'no-preference'});
  await page.locator('#toggle-entry').click();
  assert(await page.locator('#pokedex-entry').isVisible());
  assert((await page.locator('#pokedex-entry').innerText()).includes('It savagely threatens foes'));
  assert.equal(await page.locator('#toggle-entry').getAttribute('aria-expanded'),'true');
  await noOverflow();
  await page.screenshot({path:`wiki-preview/profile-${width}.png`,fullPage:false});
  await page.locator('#detail').evaluate(e=>e.scrollTop=e.scrollHeight);
  assert(await page.locator('.encounter-map').isVisible());
  assert(await page.locator('.map-highlight').count()>0);
  const closeBounds=await page.locator('#close-detail').boundingBox(),dialogBounds=await page.locator('#detail').boundingBox();
  assert(closeBounds.y<dialogBounds.y+55&&closeBounds.x>dialogBounds.x+dialogBounds.width-60,'close remains at top right while scrolling');
  await page.screenshot({path:`wiki-preview/encounter-map-${width}.png`,fullPage:false});
  await page.locator('#close-detail').click();
  await page.locator('.dex-card [data-species="POOCHYENA"]').click();
  assert.equal(await page.locator('#detail').evaluate(e=>e.scrollTop),0,'reopening resets previous profile scroll');
  assert(await page.locator('#pokedex-entry').isHidden(),'entry disclosure resets');
  assert.equal(await page.locator('#toggle-shiny').getAttribute('aria-pressed'),'false','shiny preview resets between profiles');
  await page.locator('#close-detail').click();
  await page.locator('#search').fill('');await page.locator('#type').selectOption('FIRE');
  assert((await page.locator('.dex-card .types').allTextContents()).every(t=>t.includes('fire')));
  await page.screenshot({path:`wiki-preview/dex-${width}.png`,fullPage:false});
  // A live resize preserves both the current page and selected filter.
  if(width===412){await page.setViewportSize({width:690,height:800});assert.equal(await page.locator('#type').inputValue(),'FIRE');await noOverflow();}
  await page.goto('http://127.0.0.1:8765/wiki/dex.html?view=routes');await page.locator('.route-card').first().waitFor();await noOverflow();
  await page.screenshot({path:`wiki-preview/routes-${width}.png`,fullPage:false});
  await page.locator('#method').selectOption('surf');await page.locator('[data-view="species"]').click();await page.locator('#type').selectOption('all');
  assert((await page.locator('#results-count').innerText()).startsWith('1026 '),'hidden route method must not filter the National Dex');
  assert.equal(await page.locator('.hero').evaluate(e=>getComputedStyle(e,'::before').content),'none');
  if(width===412){
    await page.goto('http://127.0.0.1:8765/wiki/dex.html?pokemon=nidoqueen');await page.locator('#detail').waitFor();
    assert((await page.locator('.detail-category').innerText()).includes('Drill Pokémon'));await page.locator('#toggle-shiny').click();
    await page.screenshot({path:'wiki-preview/nidoqueen-shiny.png',fullPage:false});
    await page.goto('http://127.0.0.1:8765/wiki/dex.html?pokemon=rattata');
    await page.locator('#detail').waitFor();
    assert.equal(await page.locator('#detail').evaluate(e=>e.scrollTop),0,'deep-linked profile opens at the top');
    assert((await page.locator('.encounter-map figcaption').allTextContents()).includes('Kanto'));
    assert.equal(await page.locator('#detail').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true,'profile must not overflow horizontally');
  }
  assert.deepEqual(errors,[]);await context.close();
 }
 await browser.close();console.log('PASS: browser navigation, search, cries, profile controls, types and overflow at 360/412/690/768/1280px, plus live fold-size change');
})().catch(e=>{console.error(e);process.exit(1);});
