"""Compile pose-aligned scarf/jacket layers into the established 4bpp avatar assets.

No silhouette, face, hand, animation ordering or held-object changes. Color slot
14 is reserved for scarves; native white highlights consolidate into near-white 9.
"""
from pathlib import Path
import json,re,sys
from PIL import Image
sys.path.insert(0,str(Path(__file__).resolve().parent))
from build_appearance import ROOT,STATES,FILES,frames,outfit_frame,skin_components,hand_pixels,ball_pixels,pack,literal_lz,c_bytes

def accessory_frame(native,gender,outfit,style,kind='overworld',pose=0,state='walking'):
    p=outfit_frame(native,gender,outfit,kind,pose,state)
    result=[[9 if v==14 else v for v in row] for row in p]
    if state=='underwater' and kind=='overworld':return result
    groups=skin_components(native)
    if not groups:return result
    face=max(groups,key=len) if kind=='overworld' else min((g for g in groups if len(g)>30),key=lambda g:min(y for x,y in g))
    fb=max(y for x,y in face);cx=round(sum(x for x,y in face)/len(face))
    h,w=len(p),len(p[0]);hands=set() if kind=='overworld' else hand_pixels(gender,kind,pose)
    balls=set() if kind=='overworld' else ball_pixels(gender,kind,pose)
    start=fb+1 if kind=='overworld' else max(fb+2,25 if kind=='front' else 38)
    end=min(h,start+(5 if kind=='overworld' else 18))
    body=set()
    for y in range(start,end):
        for x in range(w):
            if (x,y) in face|hands|balls:continue
            if kind=='overworld' and abs(x-cx)>3:continue
            if kind=='front' and not 21<=x<=38:continue
            if kind=='back' and x<14:continue
            if p[y][x] in (10,11,12,13) or (outfit==4 and p[y][x]==9):body.add((x,y))
    if not body:return result
    collar=min(y for x,y in body)
    if kind!='overworld':
        xs=[x for x,y in body if y<=collar+2];cx=round(sum(xs)/len(xs))
    if style&2:
        # Short jacket sleeves reach the upper arms, never faces or hands.
        if kind!='overworld':
            for y in range(collar,min(h,collar+9)):
                for x in range(w):
                    if native[y][x] in (1,2,3) and (x,y) not in face|hands|balls and any(abs(x-bx)+abs(y-by)<=2 for bx,by in body):
                        result[y][x]=5 if native[y][x]==1 else 6
        for x,y in body:
            result[y][x]=5 if p[y][x] in (9,10,12) else 6
        # Subtle open-jacket center seam keeps the outfit visible underneath.
        for x,y in body:
            if x==cx and y>collar+2:result[y][x]=p[y][x]
    if style&1:
        depth=3 if kind=='overworld' else 7
        for x,y in body:
            if y<=collar+(0 if kind=='overworld' else 1) or (cx<=x<=cx+(0 if kind=='overworld' else 1) and y<collar+depth):
                result[y][x]=14
    assert all((native[y][x]==0)==(result[y][x]==0) for y in range(h) for x in range(w))
    return result

def build():
    mapping=json.loads((ROOT/'tools/legends/appearance_frames.json').read_text())
    ow=['// Generated by tools/legends/build_accessories.py.\n'];trainer=[ow[0]];ids=[];entries=[];manifest={};ow_data=bytearray();trainer_data=bytearray()
    for style in (1,2,3):
        for gender,g in [('Brendan',0),('May',1)]:
            for outfit,label in enumerate(('Emerald','Trail','Sport','Yellow','Lavender')):
                prefix=f'Legends{gender}{label}Accessory{style}'
                for state,file in zip(STATES,FILES):
                    width=16 if state=='Normal' else 32
                    path=ROOT/f'graphics/object_events/pics/people/{gender.lower()}/{file}.png'
                    sources=frames(path,width,32)
                    if state=='Normal':sources+=frames(path.with_name('running.png'),16,32)
                    modified=[accessory_frame(f,g,outfit,style,pose=i,state=file) for i,f in enumerate(sources)]
                    name='s'+prefix+state;raw=b''.join(pack(f) for f in modified);ow.append(f'#define {name} (sLegendsAccessoryOverworldData + {len(ow_data)})\n');ow_data.extend(raw)
                    table=mapping[gender][state]['table'];indices=list(range(len(sources))) if 'overworld_ascending_frames' in table else [int(v) for v in re.findall(r'overworld_frame\([^,]+,\s*\d+,\s*\d+,\s*(\d+)\)',table)]
                    ow.append(f'static const struct SpriteFrameImage {name}Images[] = {{\n'+''.join(f'    {{.data={name}+{i*width*16},.size={width*16}}},\n' for i in indices)+'};\n')
                    manifest[name]={'frames':len(sources),'bytes':len(raw),'image_indices':indices}
                for kind,directory in [('Front','front_pics'),('Back','back_pics')]:
                    sources=frames(ROOT/f'graphics/trainers/{directory}/{gender.lower()}.png',64,64)
                    modified=[accessory_frame(f,g,outfit,style,kind.lower(),i) for i,f in enumerate(sources)]
                    raw=b''.join(pack(f) for f in modified);name='g'+prefix+kind
                    trainer.append(f'#define {name} ((const {"u32" if kind=="Front" else "u8"} *)(gLegendsAccessoryTrainerData + {len(trainer_data)}))\n');trainer_data.extend(literal_lz(raw) if kind=='Front' else raw)
                    manifest[name]={'frames':len(sources),'bytes':len(raw)}
                id=f'TRAINER_PIC_LEGENDS_ACCESSORY_{len(ids)}';ids.append('    '+id+',\n')
                entries.append(f'    [{id}] = {{.frontPic=TRAINER_FRONT_PIC(g{prefix}Front, gLegendsTrainerPalettes[{g}]), .backPic=TRAINER_BACK_PIC(4, g{prefix}Back, gLegendsTrainerPalettes[{g}], sBackAnims_Hoenn)}},\n')
    ow.append('static const struct SpriteFrameImage *const sLegendsAccessoryImages[3][2][5][8] = {\n')
    for style in (1,2,3):
        ow.append('    {\n')
        for gender in ('Brendan','May'):
            ow.append('        {\n')
            for label in ('Emerald','Trail','Sport','Yellow','Lavender'):
                ow.append('            {'+','.join(f'sLegends{gender}{label}Accessory{style}{state}Images' for state in STATES)+'},\n')
            ow.append('        },\n')
        ow.append('    },\n')
    ow.append('};\n')
    directory=ROOT/'graphics/legends/accessories';directory.mkdir(parents=True,exist_ok=True)
    (directory/'overworld.bin').write_bytes(ow_data);(directory/'trainers.bin').write_bytes(trainer_data)
    ow.insert(1,f'const u8 ALIGNED(4) sLegendsAccessoryOverworldData[{len(ow_data)}] = INCBIN_U8("graphics/legends/accessories/overworld.bin");\n')
    trainer.insert(1,f'const u8 ALIGNED(4) gLegendsAccessoryTrainerData[{len(trainer_data)}] = INCBIN_U8("graphics/legends/accessories/trainers.bin");\n')
    for path,data in [('src/data/legends/overworld_accessories.h',ow),('src/data/legends/trainer_accessories.h',trainer),('src/data/legends/accessory_trainers.inc',entries),('include/constants/legends_accessory_trainers.inc',ids)]:
        (ROOT/path).write_text(''.join(data))
    header=ROOT/'include/constants/trainers.h';text=header.read_text()
    marker='    // Generated accessory IDs; keep inline for the script preprocessor.'
    if marker in text:
        start=text.index(marker);end=text.index('    TRAINER_PIC_COUNT,',start)
        text=text[:start]+marker+'\n'+''.join(ids)+text[end:]
    else:
        text=text.replace('    TRAINER_PIC_COUNT,',marker+'\n'+''.join(ids)+'    TRAINER_PIC_COUNT,')
    header.write_text(text)
    (ROOT/'tools/legends/accessory_asset_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
if __name__=='__main__':build()
