"""Build pose-local footwear overlays from the native indexed player art.

Masks use 0=keep, 1=light leather, 2=shadow, 3=outline. Boots have taller
shafts, raised cuffs and separate toe/sole geometry. No ROM is needed.
"""
import json,re
from pathlib import Path
from build_appearance import ROOT,STATES,FILES,frames,pack,skin_components

def front_mask(gender,boots):
    m=[[0]*64 for _ in range(64)]
    # Independently authored left/right boot silhouettes, matching native legs.
    feet=[(19,26,57,62),(31,40,57,61)] if gender==0 else [(18,25,58,62),(32,39,58,62)]
    native=frames(ROOT/f"graphics/trainers/front_pics/{('brendan','may')[gender]}.png",64,64)[0]
    for left,right,top,bottom in feet:
        if not boots:
            # Shoes retain the native rounded toe and ankle silhouette.
            for y in range(top,bottom+1):
                for x in range(left,right+1):
                    value=native[y][x]
                    if value:m[y][x]=3 if value in (4,15) else 2 if value in (6,8,11,13) else 1
            continue
        shaft_top=48 if gender==0 else 47
        shaft_left=left+1;shaft_right=right-1
        for y in range(shaft_top,bottom):
            l=shaft_left if y<top else left
            rr=shaft_right if y<top else right
            for x in range(l,rr+1):
                if y<top:
                    if native[y][x]:m[y][x]=3 if native[y][x] in (4,15) else 2 if x>=rr-1 else 1
                else:
                    m[y][x]=3 if x in (l,rr) else 2 if x>=rr-1 else 1
        for x in range(left+1,right):m[bottom][x]=3
        if boots:
            for x in range(shaft_left,shaft_right+1):
                if native[shaft_top][x]:m[shaft_top][x]=3
            for x in range(shaft_left+1,shaft_right):
                if native[shaft_top+1][x]:m[shaft_top+1][x]=1
            # Toe highlights and a dark sole, not just recolored socks.
            for x in range(left+1,right):m[bottom-1][x]=2
    return m

def world_mask(p,boots,state):
    h,w=len(p),len(p[0]);m=[[0]*w for _ in range(h)]
    if state=='Underwater':return m
    skin=skin_components(p)
    if not skin:return m
    face=max(skin,key=len);face_bottom=max(y for x,y in face)
    center=sum(x for x,y in face)/len(face)
    remaining={(x,y) for y in range(h) for x in range(w) if p[y][x] in (10,11,12,13)}
    candidates=[]
    while remaining:
        seed=remaining.pop();group={seed};queue=[seed]
        while queue:
            x,y=queue.pop()
            for point in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
                if point in remaining:
                    remaining.remove(point);group.add(point);queue.append(point)
        # Small isolated shoe accents below the face, not gloves, clothing,
        # headbands or a fishing float. Keep the lowest accent on each leg.
        if len(group)<=10 and min(y for x,y in group)>=face_bottom+4 and all(abs(x-center)<=8 for x,y in group):
            candidates.append(group)
    if not candidates:return m
    lowest=max(max(y for x,y in group) for group in candidates)
    for side in range(2):
        groups=[group for group in candidates if max(y for x,y in group)>=lowest-2
                and (sum(x for x,y in group)/len(group)>=center)==bool(side)]
        if not groups:continue
        group=max(groups,key=lambda group:max(y for x,y in group))
        left=min(x for x,y in group)-1;right=max(x for x,y in group)+1
        top=min(y for x,y in group)-(2 if boots else 0);bottom=max(y for x,y in group)+1
        for y in range(max(0,top),min(h,bottom+1)):
            for x in range(max(0,left),min(w,right+1)):
                if p[y][x]:m[y][x]=3 if p[y][x] in (4,15) else 2 if x==right else 1
    return m

def build():
    mapping=json.loads((ROOT/'tools/legends/appearance_frames.json').read_text())
    data=bytearray();header=['// Generated by tools/legends/build_footwear.py.\n'];tables={};counts=[]
    for g,name in enumerate(('Brendan','May')):
        gc=[]
        for si,(state,file) in enumerate(zip(STATES,FILES)):
            w=16 if state=='Normal' else 32;path=ROOT/f'graphics/object_events/pics/people/{name.lower()}/{file}.png'
            src=frames(path,w,32)
            if si==0:src+=frames(path.with_name('running.png'),16,32)
            table=mapping[name][state]['table']
            idx=list(range(len(src))) if 'overworld_ascending_frames' in table else [int(v) for v in re.findall(r'overworld_frame\([^,]+,\s*\d+,\s*\d+,\s*(\d+)\)',table)]
            gc.append(len(idx))
            for boot in range(2):
                symbol=f'sFootwearMask{g}{si}{boot}';off=len(data)
                for i in idx:data.extend(pack(world_mask(src[i],boot,state)))
                header.append(f'#define {symbol} (sFootwearMaskData + {off})\n');tables[g,si,boot]=symbol
        counts.append(gc)
    for g in range(2):
        for boot in range(2):
            off=len(data);data.extend(pack(front_mask(g,boot)))
            header.append(f'#define sFootwearFront{g}{boot} (sFootwearMaskData + {off})\n')
    header.insert(1,f'static const u8 ALIGNED(4) sFootwearMaskData[] = INCBIN_U8("graphics/legends/footwear/masks.bin");\n')
    capacity=max(counts[g][st]*(256 if st==0 else 512) for g in range(2) for st in range(8))
    header.append(f'#define LEGENDS_FOOTWEAR_CACHE_BYTES {capacity}\n#define LEGENDS_FOOTWEAR_CACHE_FRAMES {max(max(x) for x in counts)}\n')
    header.append('static const u8 sFootwearFrameCount[2][8] = {'+','.join('{'+','.join(map(str,x))+'}' for x in counts)+'};\n')
    header.append('static const u8 *const sFootwearMasks[2][8][2] = {\n')
    for g in range(2):header.append('    {'+','.join('{'+','.join(tables[g,s,b] for b in range(2))+'}' for s in range(8))+'},\n')
    header.append('};\nstatic const u8 *const sFootwearFrontMasks[2][2] = {{sFootwearFront00,sFootwearFront01},{sFootwearFront10,sFootwearFront11}};\n')
    directory=ROOT/'graphics/legends/footwear';directory.mkdir(parents=True,exist_ok=True);(directory/'masks.bin').write_bytes(data)
    (ROOT/'src/data/legends/footwear_masks.h').write_text(''.join(header))
    assert max(max(x) for x in counts)<=32
    print('Footwear masks:',len(data),'bytes; frame counts:',counts)
if __name__=='__main__':build()
