// Generated by tools/legends/build_footwear.py.
static const u8 ALIGNED(4) sFootwearMaskData[] = INCBIN_U8("graphics/legends/footwear/masks.bin");
#define sFootwearMask000 (sFootwearMaskData + 0)
#define sFootwearMask001 (sFootwearMaskData + 4608)
#define sFootwearMask010 (sFootwearMaskData + 9216)
#define sFootwearMask011 (sFootwearMaskData + 13824)
#define sFootwearMask020 (sFootwearMaskData + 18432)
#define sFootwearMask021 (sFootwearMaskData + 32256)
#define sFootwearMask030 (sFootwearMaskData + 46080)
#define sFootwearMask031 (sFootwearMaskData + 52224)
#define sFootwearMask040 (sFootwearMaskData + 58368)
#define sFootwearMask041 (sFootwearMaskData + 62976)
#define sFootwearMask050 (sFootwearMaskData + 67584)
#define sFootwearMask051 (sFootwearMaskData + 70144)
#define sFootwearMask060 (sFootwearMaskData + 72704)
#define sFootwearMask061 (sFootwearMaskData + 78848)
#define sFootwearMask070 (sFootwearMaskData + 84992)
#define sFootwearMask071 (sFootwearMaskData + 89600)
#define sFootwearMask100 (sFootwearMaskData + 94208)
#define sFootwearMask101 (sFootwearMaskData + 98816)
#define sFootwearMask110 (sFootwearMaskData + 103424)
#define sFootwearMask111 (sFootwearMaskData + 108032)
#define sFootwearMask120 (sFootwearMaskData + 112640)
#define sFootwearMask121 (sFootwearMaskData + 126464)
#define sFootwearMask130 (sFootwearMaskData + 140288)
#define sFootwearMask131 (sFootwearMaskData + 146432)
#define sFootwearMask140 (sFootwearMaskData + 152576)
#define sFootwearMask141 (sFootwearMaskData + 157184)
#define sFootwearMask150 (sFootwearMaskData + 161792)
#define sFootwearMask151 (sFootwearMaskData + 164352)
#define sFootwearMask160 (sFootwearMaskData + 166912)
#define sFootwearMask161 (sFootwearMaskData + 173056)
#define sFootwearMask170 (sFootwearMaskData + 179200)
#define sFootwearMask171 (sFootwearMaskData + 183808)
#define sFootwearFront00 (sFootwearMaskData + 188416)
#define sFootwearFront01 (sFootwearMaskData + 190464)
#define sFootwearFront10 (sFootwearMaskData + 192512)
#define sFootwearFront11 (sFootwearMaskData + 194560)
static const u8 sFootwearFrameCount[2][8] = {{18,9,27,12,9,5,12,9},{18,9,27,12,9,5,12,9}};
static const u8 *const sFootwearMasks[2][8][2] = {
    {{sFootwearMask000,sFootwearMask001},{sFootwearMask010,sFootwearMask011},{sFootwearMask020,sFootwearMask021},{sFootwearMask030,sFootwearMask031},{sFootwearMask040,sFootwearMask041},{sFootwearMask050,sFootwearMask051},{sFootwearMask060,sFootwearMask061},{sFootwearMask070,sFootwearMask071}},
    {{sFootwearMask100,sFootwearMask101},{sFootwearMask110,sFootwearMask111},{sFootwearMask120,sFootwearMask121},{sFootwearMask130,sFootwearMask131},{sFootwearMask140,sFootwearMask141},{sFootwearMask150,sFootwearMask151},{sFootwearMask160,sFootwearMask161},{sFootwearMask170,sFootwearMask171}},
};
static const u8 *const sFootwearFrontMasks[2][2] = {{sFootwearFront00,sFootwearFront01},{sFootwearFront10,sFootwearFront11}};
