#!/usr/bin/env python3
"""Bundle all documented Pokémon icons from the wiki's manually pinned snapshot."""
from collections import deque
from io import BytesIO
from pathlib import Path
import json
import math
import subprocess
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'docs/wiki/dex-data.json').read_text())
icons = sorted({p.get('sprite') or p['id'].lower() for p in data['species']})
columns, side = 32, 32
atlas = Image.new('RGBA', (columns * side, math.ceil(len(icons) / columns) * side))
positions = {}
for index, icon in enumerate(icons):
    source = subprocess.check_output(['git', 'show', data['sourceCommit'] + ':graphics/pokemon/' + icon + '/icon.png'], cwd=ROOT)
    sheet = Image.open(BytesIO(source)).convert('RGBA')
    assert sheet.width == side and sheet.height >= side
    frame = sheet.crop((0, 0, side, side))
    bg, seen = frame.getpixel((0, 0)), set()
    queue = deque([(x, 0) for x in range(side)] + [(x, side-1) for x in range(side)] + [(0, y) for y in range(side)] + [(side-1, y) for y in range(side)])
    while queue:
        x, y = queue.popleft()
        if (x, y) in seen or not (0 <= x < side and 0 <= y < side):
            continue
        seen.add((x, y))
        pixel = frame.getpixel((x, y))
        if pixel != bg and pixel[3] != 0:
            continue
        frame.putpixel((x, y), (0, 0, 0, 0))
        queue.extend(((x-1, y), (x+1, y), (x, y-1), (x, y+1)))
    bbox = frame.getbbox()
    assert bbox is not None, icon
    silhouette = frame.crop(bbox)
    centered = Image.new('RGBA', (side, side))
    centered.alpha_composite(silhouette, ((side-silhouette.width)//2, (side-silhouette.height)//2))
    x, y = index % columns, index // columns
    atlas.alpha_composite(centered, (x*side, y*side))
    positions[icon] = [x, y]
target = ROOT / 'docs/wiki'
atlas.save(target / 'dex-sprite-atlas.webp', format="WEBP", lossless=True, method=6)
metadata = dict(sourceCommit=data['sourceCommit'], url='dex-sprite-atlas.webp', columns=columns, rows=atlas.height//side, icons=positions)
(target / 'dex-sprite-atlas.js').write_text('/* Generated by tools/build_wiki_sprite_atlas.py; pinned wiki snapshot. */\nwindow.LegendsSpriteAtlas=' + json.dumps(metadata, separators=(',', ':')) + ';\n')
print(f'Bundled {len(icons)} transparent icons: {(target / "dex-sprite-atlas.webp").stat().st_size} bytes')
